### PR TITLE
before_filter is deprecated and will be removed in Rails 5.1

### PR DESCRIPTION
**Pull request by fredngo**
It would be highly appreciated if you could merge this PR and cut a new release -- this problem blocks upgrades to Rails 5.1 !

### CODE REVIEW

**Comment by NathanielTurner** [comment]
I second this. Been seeing the before filter warning in my console for many months now and I finally know whats causing it. Please merge this as I would rather that than monkey patching the module.

**Comment by fredngo** [comment]
I've upgraded to Rails 5.1 using my own branch of Paloma (https://github.com/fredngo/paloma) right now but a release to Rubygems would be very much appreciated.

**Review by brunopascoa — APPROVED** [review]

**Comment by fredngo** [comment]
So, will this be merged soon? :)

**Comment by andreibondarev** [comment]
@jonatasrancan FYI

**Comment by jonatasrancan** [comment]
:eyes:

**Comment by etewiah** [comment]
Guys, would really appreciate this being merged.  Got someone raising an issue with my propertywebbuilder gem because of this:

https://github.com/etewiah/property_web_builder/issues/28

I will use the fork for now but would be great to not have to.

Thanks ;)

**Review by stephannv — APPROVED** [review]

**Review by mati-a — APPROVED** [review]

**Comment by fredngo** [comment]
A lot of approvals, which is nice, but can we get a release plz? :)

**Review by daniffig — APPROVED** [review]

**Comment by daniffig** [comment]
It would be nice if you merge this.

**Comment by fredngo** [comment]
Earth calling @gnclmorais , come in @gnclmorais ... Does anyone know (or can figure out) Gonçalo's email address?

**Comment by etewiah** [comment]
Can't figure out his email but just sent him a tweet:  https://twitter.com/gnclmorais

**Comment by gnclmorais** [comment]
Hey folks! Sorry for the late reply, this fell out of my radar (for some reason)… I’ll look into this soon! 👌

**Comment by gnclmorais** [comment]
✨  _Stellar work_, folks… I’m going to release a new version in a few minutes (5.1.0, so it goes well with Rails 5.1). 💎

**Comment by gnclmorais** [comment]
[📣  And we’re live!](https://rubygems.org/gems/paloma/versions/5.1.0)

**Pull request merged**
